"""
Knowledge Base Deep Engine Package
"""

from main.utils.kb_engine.classifier import (
    DEFAULT_LOCAL_MODEL,
    CanonicalCategory,
    CanonicalTopic,
    DocumentTaggingResult,
    FakeModelAdapter,
    LocalLLMClassifier,
    MLXAdapter,
    ModelAdapter,
    OllamaAdapter,
    apply_tags_to_file,
    classify_content,
    classify_document,
    create_model_adapter,
)
from main.utils.kb_engine.engine import KBEngine
from main.utils.kb_engine.errors import (
    CorpusChangedDuringSyncError,
    EmptyCorpusError,
    IndexNotBuiltError,
    InvalidIndexError,
    InvalidIndexPathError,
    InvalidKnowledgeBaseError,
    InvalidKnowledgeSourceError,
    InvalidSearchError,
    InvalidTaxonomyError,
    KBEngineError,
    KnowledgeBaseNotFoundError,
    KnowledgeSourceNotFoundError,
    MissingDependencyError,
    ModelConnectionError,
    ModelInferenceError,
    StaleIndexError,
    UnsupportedLanguageError,
)
from main.utils.kb_engine.frontmatter import KnowledgeSource
from main.utils.kb_engine.models import (
    EvidencePassage,
    EvidenceSearchResult,
    IndexBuildMetrics,
    IndexStatus,
)
from main.utils.kb_engine.taxonomy import TaxonomyRegistry

__all__ = [
    "CorpusChangedDuringSyncError",
    "CanonicalCategory",
    "CanonicalTopic",
    "DEFAULT_LOCAL_MODEL",
    "DocumentTaggingResult",
    "EmptyCorpusError",
    "EvidencePassage",
    "EvidenceSearchResult",
    "FakeModelAdapter",
    "IndexNotBuiltError",
    "IndexBuildMetrics",
    "IndexStatus",
    "InvalidIndexError",
    "InvalidIndexPathError",
    "InvalidKnowledgeBaseError",
    "InvalidKnowledgeSourceError",
    "InvalidSearchError",
    "InvalidTaxonomyError",
    "KBEngine",
    "KBEngineError",
    "KnowledgeBaseNotFoundError",
    "KnowledgeSource",
    "KnowledgeSourceNotFoundError",
    "LocalLLMClassifier",
    "MLXAdapter",
    "MissingDependencyError",
    "ModelAdapter",
    "ModelConnectionError",
    "ModelInferenceError",
    "OllamaAdapter",
    "StaleIndexError",
    "TaxonomyRegistry",
    "UnsupportedLanguageError",
    "apply_tags_to_file",
    "classify_content",
    "classify_document",
    "create_model_adapter",
]
