"""
Domain terminology synonyms and stop-word dictionaries for the
Endurance Training Knowledge Base.
"""

from __future__ import annotations

from collections.abc import Sequence

# Stop words to filter from conversational queries
STOP_WORDS: frozenset[str] = frozenset(
    {
        "a",
        "about",
        "above",
        "after",
        "again",
        "against",
        "all",
        "am",
        "an",
        "and",
        "any",
        "are",
        "aren't",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "can't",
        "cannot",
        "could",
        "did",
        "do",
        "does",
        "doing",
        "don't",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "i",
        "if",
        "in",
        "into",
        "is",
        "isn't",
        "it",
        "its",
        "itself",
        "let's",
        "me",
        "more",
        "most",
        "my",
        "myself",
        "no",
        "nor",
        "not",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "ought",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "own",
        "same",
        "she",
        "should",
        "so",
        "some",
        "such",
        "than",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "very",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "with",
        "would",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
        # Conversational / generic prompt fillers
        "occur",
        "occurs",
        "occurred",
        "occurring",
        "changes",
        "describe",
        "describes",
        "tell",
        "explain",
        "versus",
        "vs",
        "yield",
        "yields",
        "give",
        "gives",
    }
)


# Broaden the conventional list for conversational Athlete Queries. Generic NLP
# stoplists are unsafe here because they commonly discard useful training intent.
# Keep negation, comparison, timing, magnitude, and numeric language searchable.
def _word_set(words: str) -> frozenset[str]:
    return frozenset(words.split())


_MEANING_BEARING_WORDS = _word_set(
    """
    above after against before below between changes during less more most no nor
    not only under until versus vs yield yields
    """
)

_ADDITIONAL_STOP_WORDS = _word_set(
    """
    already although also always another anybody anyone anything anyhow anyway
    anywhere aren't beside besides both cannot could did didn't does doesn't don't
    either else elsewhere enough every everybody everyone everything everywhere
    finally furthermore hadn't hasn't haven't hence however indeed inside instead
    just many may meanwhile might mine moreover mostly much must namely neither
    nobody none nothing now nowhere often one onto otherwise outside perhaps please
    rather really several shall shan't somebody somehow someone something sometimes
    somewhere still therefore throughout thus together toward towards upon us
    usually via wasn't weren't whatever whereby wherein wherever whether whichever
    whoever whomever whose will won't within answer answers compare compared
    comparing comparison comparisons described describing detail details explained
    explaining explains given giving help know mean means show shows tells
    i'd i'll i'm i've he'd he'll he's she'd she'll she's it'd it'll it's we'd we'll
    we're we've they'd they'll they're they've you'd you'll you're you've that's
    there's here's what's where's who's how's when's why's couldn't shouldn't
    wouldn't mightn't mustn't needn't okay ok need needs needed needing provide
    provides say says discuss discusses
    """
)

STOP_WORDS = (STOP_WORDS | _ADDITIONAL_STOP_WORDS) - _MEANING_BEARING_WORDS

# Canonical domain synonym mapping
DOMAIN_SYNONYMS: dict[str, tuple[str, ...]] = {
    # -------------------------------------------------------------------------
    # GENERAL DOMAIN
    # -------------------------------------------------------------------------
    "endurance_training": (
        "endurance training",
        "endurance exercise",
        "aerobic training",
        "aerobic exercise",
        "cardiorespiratory training",
        "cardiovascular training",
        "cardio training",
        "conditioning",
        "endurance conditioning",
        "aerobic conditioning",
        "stamina training",
        "long distance training",
        "distance training",
        "prolonged exercise",
        "endurance sport",
        "endurance sports",
    ),
    "strength_training": (
        "strength training",
        "strenght training",
        "resistance training",
        "resistance exercise",
        "weight training",
        "weightlifting",
        "weight lifting",
        "lifting",
        "strength exercise",
        "muscular strength training",
        "progressive resistance training",
        "progressive resistance exercise",
        "prt",
        "gym training",
        "dryland training",
        "strength and conditioning",
        "s&c",
    ),
    "exercise_physiology": (
        "exercise physiology",
        "sport physiology",
        "sports physiology",
        "physiology of sport",
        "physiology of exercise",
        "human exercise physiology",
        "applied exercise physiology",
        "performance physiology",
        "training physiology",
        "exercise science",
        "sport science",
        "sports science",
    ),
    "sport_science": (
        "sport science",
        "sports science",
        "exercise science",
        "human performance",
        "human performance science",
        "performance science",
        "sport performance",
        "sports performance",
        "exercise physiology",
        "kinesiology",
        "strength and conditioning",
        "sport biomechanics",
        "sports biomechanics",
        "training science",
        "coaching science",
    ),
    "kinesiology": (
        "kinesiology",
        "human movement",
        "human movement science",
        "movement science",
        "exercise science",
        "biomechanics",
        "motor control",
        "motor behavior",
    ),
    "sports_medicine": (
        "sports medicine",
        "sport medicine",
        "exercise medicine",
        "sports injury",
        "sports injuries",
        "injury prevention",
        "rehabilitation",
        "return to sport",
        "return to play",
    ),
    "strength_and_conditioning": (
        "strength and conditioning",
        "strength & conditioning",
        "s&c",
        "physical preparation",
        "athletic development",
        "athletic preparation",
        "performance training",
        "sports performance training",
    ),
    # -------------------------------------------------------------------------
    # AEROBIC CAPACITY AND OXYGEN UPTAKE
    # -------------------------------------------------------------------------
    "vo2": (
        "vo2",
        "v̇o2",
        "oxygen uptake",
        "oxygen consumption",
        "aerobic metabolism",
        "oxygen utilization",
        "oxygen utilisation",
    ),
    "vo2max": (
        "vo2max",
        "vo2 max",
        "v̇o2max",
        "maximal oxygen uptake",
        "maximum oxygen uptake",
        "maximal oxygen consumption",
        "maximum oxygen consumption",
        "maximal aerobic capacity",
        "aerobic capacity",
        "peak oxygen uptake",
        "vo2peak",
        "vo2 peak",
        "cardiorespiratory fitness",
        "aerobic fitness",
    ),
    "vo2peak": (
        "vo2peak",
        "vo2 peak",
        "peak vo2",
        "peak oxygen uptake",
        "peak oxygen consumption",
        "vo2max",
        "maximal oxygen uptake",
    ),
    "vo2_kinetics": (
        "vo2 kinetics",
        "oxygen uptake kinetics",
        "oxygen consumption kinetics",
        "vo2 response",
        "on kinetics",
        "off kinetics",
        "oxygen deficit",
        "primary component",
        "slow component",
        "vo2 slow component",
        "tau vo2",
        "time constant",
    ),
    "vo2_slow_component": (
        "vo2 slow component",
        "oxygen uptake slow component",
        "slow component",
        "excess vo2",
        "vo2 drift",
        "oxygen consumption drift",
    ),
    "vvo2max": (
        "vvo2max",
        "vvo2 max",
        "velocity at vo2max",
        "velocity associated with vo2max",
        "maximal aerobic speed",
        "mas",
        "aerobic speed",
    ),
    "pvo2max": (
        "pvo2max",
        "pvo2 max",
        "power at vo2max",
        "power associated with vo2max",
        "maximal aerobic power",
        "map",
        "aerobic power",
    ),
    "maximal_aerobic_speed": (
        "maximal aerobic speed",
        "maximum aerobic speed",
        "mas",
        "vvo2max",
        "velocity at vo2max",
        "aerobic speed",
    ),
    "maximal_aerobic_power": (
        "maximal aerobic power",
        "maximum aerobic power",
        "map",
        "pvo2max",
        "power at vo2max",
        "aerobic power",
    ),
    "aerobic_capacity": (
        "aerobic capacity",
        "maximal aerobic capacity",
        "aerobic fitness",
        "cardiorespiratory fitness",
        "cardiovascular fitness",
        "vo2max",
        "endurance capacity",
    ),
    "aerobic_power": (
        "aerobic power",
        "maximal aerobic power",
        "map",
        "pvo2max",
        "vo2max power",
        "high aerobic power",
    ),
    # -------------------------------------------------------------------------
    # THRESHOLDS AND EXERCISE-INTENSITY DOMAINS
    # -------------------------------------------------------------------------
    "ftp": (
        "ftp",
        "functional threshold power",
        "functional threshold",
        "threshold power",
        "cycling threshold",
        "one hour power",
        "60 minute power",
        "critical power",
        "cp",
        "mlss",
        "maximal lactate steady state",
        "lt2",
        "second lactate threshold",
    ),
    "critical_power": (
        "critical power",
        "cp",
        "critical wattage",
        "critical intensity",
        "critical power model",
        "power duration relationship",
        "power-duration relationship",
        "hyperbolic power duration",
        "ftp",
        "maximum metabolic steady state",
    ),
    "critical_speed": (
        "critical speed",
        "cs",
        "critical velocity",
        "cv",
        "critical running speed",
        "critical swimming speed",
        "critical swim speed",
        "css",
        "velocity duration relationship",
        "speed duration relationship",
    ),
    "critical_velocity": (
        "critical velocity",
        "cv",
        "critical speed",
        "cs",
        "velocity duration relationship",
        "critical running velocity",
    ),
    "maximum_metabolic_steady_state": (
        "maximum metabolic steady state",
        "maximal metabolic steady state",
        "mmss",
        "critical power",
        "critical speed",
        "mlss",
        "threshold",
        "heavy severe boundary",
    ),
    "mlss": (
        "mlss",
        "maximal lactate steady state",
        "maximum lactate steady state",
        "lactate steady state",
        "maximal steady state",
        "threshold",
        "lt2",
        "ftp",
        "critical power",
        "anaerobic threshold",
    ),
    "lactate_threshold": (
        "lactate threshold",
        "lt",
        "blood lactate threshold",
        "lactate turnpoint",
        "lactate breakpoint",
        "lactate inflection point",
        "anaerobic threshold",
        "aerobic threshold",
        "first lactate threshold",
        "second lactate threshold",
    ),
    "lt1": (
        "lt1",
        "lt 1",
        "lactate threshold 1",
        "first lactate threshold",
        "first threshold",
        "aerobic threshold",
        "aet",
        "vt1",
        "ventilatory threshold 1",
        "gas exchange threshold",
        "get",
        "lactate turnpoint 1",
        "lactate breakpoint 1",
        "lower threshold",
    ),
    "lt2": (
        "lt2",
        "lt 2",
        "lactate threshold 2",
        "second lactate threshold",
        "second threshold",
        "anaerobic threshold",
        "ant",
        "vt2",
        "ventilatory threshold 2",
        "respiratory compensation point",
        "rcp",
        "lactate turnpoint 2",
        "lactate breakpoint 2",
        "upper threshold",
        "mlss",
    ),
    "vt1": (
        "vt1",
        "vt 1",
        "ventilatory threshold 1",
        "first ventilatory threshold",
        "gas exchange threshold",
        "get",
        "aerobic threshold",
        "lt1",
        "first threshold",
    ),
    "vt2": (
        "vt2",
        "vt 2",
        "ventilatory threshold 2",
        "second ventilatory threshold",
        "respiratory compensation point",
        "rcp",
        "anaerobic threshold",
        "lt2",
        "second threshold",
    ),
    "gas_exchange_threshold": (
        "gas exchange threshold",
        "get",
        "ventilatory threshold",
        "vt1",
        "first ventilatory threshold",
        "aerobic threshold",
        "lt1",
    ),
    "respiratory_compensation_point": (
        "respiratory compensation point",
        "rcp",
        "respiratory compensation threshold",
        "ventilatory threshold 2",
        "vt2",
        "second ventilatory threshold",
        "hyperventilation threshold",
    ),
    "aerobic_threshold": (
        "aerobic threshold",
        "aet",
        "aerobic threshold heart rate",
        "first threshold",
        "lt1",
        "vt1",
        "gas exchange threshold",
        "lower threshold",
        "lactate threshold 1",
    ),
    "anaerobic_threshold": (
        "anaerobic threshold",
        "ant",
        "second threshold",
        "lt2",
        "vt2",
        "mlss",
        "upper threshold",
        "lactate threshold 2",
        "respiratory compensation point",
    ),
    "obla": (
        "obla",
        "onset of blood lactate accumulation",
        "4 mmol threshold",
        "four millimole threshold",
        "fixed blood lactate threshold",
        "lactate threshold",
        "anaerobic threshold",
    ),
    "lactate_turnpoint": (
        "lactate turnpoint",
        "lactate turn point",
        "lactate breakpoint",
        "lactate inflection",
        "lactate threshold",
        "ltp1",
        "ltp2",
    ),
    "moderate_domain": (
        "moderate domain",
        "moderate intensity domain",
        "moderate exercise",
        "below lt1",
        "below vt1",
        "below gas exchange threshold",
        "steady state exercise",
    ),
    "heavy_domain": (
        "heavy domain",
        "heavy intensity domain",
        "heavy exercise",
        "between thresholds",
        "between lt1 and lt2",
        "between vt1 and vt2",
        "positive vo2 slow component",
    ),
    "severe_domain": (
        "severe domain",
        "severe intensity domain",
        "severe exercise",
        "above critical power",
        "above critical speed",
        "above mlss",
        "vo2max domain",
        "non steady state exercise",
    ),
    "extreme_domain": (
        "extreme domain",
        "extreme intensity domain",
        "extreme exercise",
        "sprint intensity",
        "supramaximal exercise",
        "exhaustion before vo2max",
    ),
    # -------------------------------------------------------------------------
    # ANAEROBIC CAPACITY AND POWER-DURATION MODELS
    # -------------------------------------------------------------------------
    "w_prime": (
        "w'",
        "w prime",
        "w_prime",
        "w-prime",
        "anaerobic work capacity",
        "work above critical power",
        "finite work capacity",
        "curvature constant",
        "critical power reserve",
    ),
    "w_prime_balance": (
        "w prime balance",
        "w' balance",
        "wbal",
        "w'bal",
        "w prime depletion",
        "w prime recovery",
        "anaerobic work capacity balance",
    ),
    "d_prime": (
        "d'",
        "d prime",
        "d_prime",
        "distance above critical speed",
        "finite distance capacity",
        "critical speed reserve",
        "anaerobic distance capacity",
    ),
    "anaerobic_capacity": (
        "anaerobic capacity",
        "anaerobic work capacity",
        "w prime",
        "w'",
        "glycolytic capacity",
        "oxygen deficit",
        "maximal accumulated oxygen deficit",
        "maod",
    ),
    "anaerobic_power": (
        "anaerobic power",
        "peak power",
        "sprint power",
        "maximal power",
        "maximum power",
        "explosive power",
        "wingate peak power",
    ),
    "glycolytic_power": (
        "glycolytic power",
        "glycolytic rate",
        "glycolytic capacity",
        "anaerobic glycolysis",
        "lactate production",
        "vlamax",
        "maximal lactate production rate",
    ),
    "vlamax": (
        "vlamax",
        "vlamax",
        "maximal lactate production rate",
        "maximum lactate production rate",
        "maximal glycolytic rate",
        "glycolytic power",
        "glycolytic capacity",
    ),
    "oxygen_deficit": (
        "oxygen deficit",
        "accumulated oxygen deficit",
        "maximal accumulated oxygen deficit",
        "maod",
        "anaerobic capacity",
        "energy deficit",
    ),
    "power_duration": (
        "power duration",
        "power-duration",
        "power duration curve",
        "power-duration curve",
        "power duration relationship",
        "power profile",
        "mean maximal power",
        "mmp",
        "critical power model",
    ),
    "speed_duration": (
        "speed duration",
        "speed-duration",
        "speed duration curve",
        "velocity duration relationship",
        "critical speed model",
        "running power duration",
    ),
    # -------------------------------------------------------------------------
    # ENDURANCE PERFORMANCE
    # -------------------------------------------------------------------------
    "tte": (
        "tte",
        "time to exhaustion",
        "time until exhaustion",
        "time to task failure",
        "exercise tolerance",
        "endurance time",
        "limit time",
        "tlim",
        "time limit",
    ),
    "time_trial": (
        "time trial",
        "tt",
        "self paced trial",
        "self-paced trial",
        "performance trial",
        "race simulation",
        "distance trial",
        "cycling time trial",
        "running time trial",
    ),
    "durability": (
        "durability",
        "physiological durability",
        "performance durability",
        "fatigue resistance",
        "resistance to fatigue",
        "physiological resilience",
        "performance resilience",
        "late race performance",
        "performance after prolonged exercise",
    ),
    "fatigue_resistance": (
        "fatigue resistance",
        "resistance to fatigue",
        "durability",
        "strength endurance",
        "muscular endurance",
        "repeatability",
        "performance maintenance",
    ),
    "aerobic_decoupling": (
        "aerobic decoupling",
        "decoupling",
        "heart rate decoupling",
        "power heart rate decoupling",
        "pace heart rate decoupling",
        "cardiac drift",
        "efficiency factor drift",
        "pw:hr",
        "pa:hr",
    ),
    "cardiovascular_drift": (
        "cardiovascular drift",
        "cardiac drift",
        "heart rate drift",
        "progressive heart rate increase",
        "stroke volume drift",
        "thermal drift",
    ),
    "running_economy": (
        "running economy",
        "running efficiency",
        "oxygen cost of running",
        "energy cost of running",
        "metabolic cost of running",
        "submaximal oxygen cost",
    ),
    "cycling_efficiency": (
        "cycling efficiency",
        "cycling economy",
        "gross efficiency",
        "delta efficiency",
        "net efficiency",
        "mechanical efficiency",
        "metabolic efficiency",
        "oxygen cost of cycling",
    ),
    "exercise_economy": (
        "exercise economy",
        "movement economy",
        "locomotion economy",
        "oxygen cost",
        "energy cost",
        "metabolic cost",
        "running economy",
        "cycling efficiency",
    ),
    "gross_efficiency": (
        "gross efficiency",
        "ge",
        "cycling efficiency",
        "mechanical efficiency",
        "external work efficiency",
        "power to metabolic cost ratio",
    ),
    "pacing": (
        "pacing",
        "pacing strategy",
        "pace distribution",
        "power distribution",
        "effort distribution",
        "self pacing",
        "self-paced exercise",
        "negative split",
        "positive split",
        "even pacing",
    ),
    # -------------------------------------------------------------------------
    # TRAINING INTENSITY AND ZONES
    # -------------------------------------------------------------------------
    "training_intensity": (
        "training intensity",
        "exercise intensity",
        "workout intensity",
        "relative intensity",
        "absolute intensity",
        "intensity domain",
        "training zone",
        "effort level",
    ),
    "zone1": (
        "zone 1",
        "zone1",
        "z1",
        "recovery zone",
        "easy zone",
        "low intensity",
        "active recovery",
        "below aerobic threshold",
    ),
    "zone2": (
        "zone 2",
        "zone2",
        "z2",
        "aerobic base",
        "base training",
        "endurance zone",
        "low intensity",
        "low intensity training",
        "lit",
        "steady aerobic",
        "conversational pace",
        "fat oxidation",
        "mitochondrial training",
        "below lt1",
        "below vt1",
    ),
    "zone3": (
        "zone 3",
        "zone3",
        "z3",
        "tempo",
        "moderate intensity",
        "middle zone",
        "between thresholds",
        "grey zone",
        "gray zone",
    ),
    "zone4": (
        "zone 4",
        "zone4",
        "z4",
        "threshold zone",
        "lactate threshold",
        "functional threshold",
        "ftp zone",
        "high intensity",
    ),
    "zone5": (
        "zone 5",
        "zone5",
        "z5",
        "vo2max zone",
        "maximal aerobic power",
        "high intensity",
        "severe intensity",
        "vo2 intervals",
    ),
    "zone6": (
        "zone 6",
        "zone6",
        "z6",
        "anaerobic capacity",
        "supramaximal",
        "sprint zone",
        "glycolytic zone",
    ),
    "low_intensity_training": (
        "low intensity training",
        "low-intensity training",
        "lit",
        "easy training",
        "easy endurance",
        "aerobic base",
        "base training",
        "zone 1 training",
        "zone 2 training",
        "subthreshold training",
    ),
    "moderate_intensity_training": (
        "moderate intensity training",
        "moderate-intensity training",
        "mit",
        "tempo training",
        "middle intensity",
        "between thresholds",
        "zone 3 training",
    ),
    "high_intensity_training": (
        "high intensity training",
        "high-intensity training",
        "hit",
        "hiit",
        "interval training",
        "hard training",
        "high intensity exercise",
        "vigorous exercise",
    ),
    "hiit": (
        "hiit",
        "hit",
        "high intensity interval training",
        "high-intensity interval training",
        "high intensity intervals",
        "interval training",
        "aerobic intervals",
        "vo2max intervals",
        "vo2 intervals",
        "work recovery intervals",
        "intermittent exercise",
    ),
    "sit": (
        "sit",
        "sprint interval training",
        "sprint intervals",
        "all out intervals",
        "all-out intervals",
        "supramaximal intervals",
        "wingate intervals",
        "repeated sprints",
    ),
    "repeated_sprint_training": (
        "repeated sprint training",
        "repeated sprint exercise",
        "repeated sprint ability",
        "rsa",
        "repeated sprints",
        "sprint interval training",
        "sprint repeat training",
    ),
    "threshold_training": (
        "threshold training",
        "threshold intervals",
        "lactate threshold training",
        "anaerobic threshold training",
        "ftp training",
        "mlss training",
        "tempo intervals",
        "subthreshold training",
    ),
    "tempo_training": (
        "tempo training",
        "tempo",
        "steady tempo",
        "moderate intensity training",
        "zone 3",
        "subthreshold",
        "marathon pace",
        "sustained effort",
    ),
    "sweet_spot": (
        "sweet spot",
        "sweetspot",
        "sweet spot training",
        "subthreshold",
        "high tempo",
        "lower threshold",
        "88 to 94 percent ftp",
        "near threshold",
    ),
    "over_under": (
        "over under",
        "over-under",
        "over unders",
        "over-unders",
        "crisscross intervals",
        "micro variations",
        "threshold alternations",
        "lactate clearance intervals",
    ),
    "fartlek": (
        "fartlek",
        "speed play",
        "unstructured intervals",
        "variable pace training",
        "pace variation",
    ),
    "long_slow_distance": (
        "long slow distance",
        "lsd",
        "long distance training",
        "steady state endurance",
        "easy long run",
        "long ride",
        "long aerobic session",
    ),
    "long_interval": (
        "long intervals",
        "long interval training",
        "long work intervals",
        "vo2max intervals",
        "aerobic power intervals",
        "three minute intervals",
        "four minute intervals",
        "five minute intervals",
    ),
    "short_interval": (
        "short intervals",
        "short interval training",
        "micro intervals",
        "intermittent intervals",
        "thirty thirty intervals",
        "30/30",
        "forty twenty intervals",
        "40/20",
        "fifteen fifteen intervals",
        "15/15",
    ),
    "interval_training": (
        "interval training",
        "intervals",
        "intermittent training",
        "work rest intervals",
        "work recovery intervals",
        "hiit",
        "high intensity interval training",
        "repetition training",
    ),
    # -------------------------------------------------------------------------
    # TRAINING-INTENSITY DISTRIBUTION
    # -------------------------------------------------------------------------
    "polarized_training": (
        "polarized training",
        "polarised training",
        "polarized intensity distribution",
        "polarised intensity distribution",
        "polarized model",
        "80/20 training",
        "80 20 training",
        "mostly easy training",
        "low intensity high intensity",
    ),
    "pyramidal_training": (
        "pyramidal training",
        "pyramidal intensity distribution",
        "pyramidal model",
        "pyramidal training intensity distribution",
        "mostly low intensity",
    ),
    "threshold_model": (
        "threshold model",
        "threshold training distribution",
        "threshold intensity distribution",
        "threshold focused training",
        "threshold-dominant training",
    ),
    "training_intensity_distribution": (
        "training intensity distribution",
        "tid",
        "intensity distribution",
        "training zone distribution",
        "polarized training",
        "pyramidal training",
        "threshold training",
        "three zone model",
        "five zone model",
        "seven zone model",
    ),
    "norwegian": (
        "norwegian",
        "norwegian method",
        "norwegian model",
        "norwegian training",
        "double threshold",
        "double threshold training",
        "controlled threshold",
        "subthreshold",
        "lactate controlled training",
        "lactate guided training",
        "threshold singles",
        "single threshold",
    ),
    "double_threshold": (
        "double threshold",
        "double threshold day",
        "double threshold training",
        "two threshold sessions",
        "am pm threshold",
        "norwegian method",
        "norwegian model",
        "lactate controlled threshold",
    ),
    # -------------------------------------------------------------------------
    # PERIODIZATION AND PROGRAMMING
    # -------------------------------------------------------------------------
    "periodization": (
        "periodization",
        "periodisation",
        "training periodization",
        "training periodisation",
        "periodized training",
        "periodised training",
        "training planning",
        "annual training plan",
        "season planning",
    ),
    "linear_periodization": (
        "linear periodization",
        "linear periodisation",
        "traditional periodization",
        "traditional periodisation",
        "progressive periodization",
    ),
    "undulating_periodization": (
        "undulating periodization",
        "undulating periodisation",
        "daily undulating periodization",
        "dup",
        "weekly undulating periodization",
        "wup",
        "nonlinear periodization",
    ),
    "block_periodization": (
        "block periodization",
        "block periodisation",
        "block training",
        "concentrated loading",
        "accumulation transmutation realization",
        "atr",
    ),
    "reverse_periodization": (
        "reverse periodization",
        "reverse periodisation",
        "reverse linear periodization",
        "intensity first periodization",
    ),
    "base_training": (
        "base training",
        "aerobic base",
        "base phase",
        "general preparation",
        "foundation training",
        "aerobic development",
        "endurance base",
        "high volume low intensity",
    ),
    "build_phase": (
        "build phase",
        "specific preparation",
        "pre competition phase",
        "pre-competition phase",
        "race specific training",
        "intensification phase",
    ),
    "peak_phase": (
        "peak phase",
        "peaking",
        "competition phase",
        "race preparation",
        "performance peak",
        "taper phase",
    ),
    "taper": (
        "taper",
        "tapering",
        "pre competition taper",
        "pre-competition taper",
        "training reduction",
        "volume reduction",
        "exponential taper",
        "step taper",
        "peaking",
    ),
    "deload": (
        "deload",
        "deload week",
        "recovery week",
        "unloading week",
        "reduced load",
        "planned recovery",
        "volume reduction",
    ),
    "progressive_overload": (
        "progressive overload",
        "training progression",
        "progressive loading",
        "load progression",
        "overload principle",
        "gradual overload",
    ),
    "specificity": (
        "specificity",
        "training specificity",
        "specific adaptation",
        "said principle",
        "specific adaptation to imposed demands",
        "sport specific training",
    ),
    "overload": (
        "overload",
        "training overload",
        "overload stimulus",
        "progressive overload",
        "functional overload",
    ),
    "supercompensation": (
        "supercompensation",
        "fitness rebound",
        "adaptation rebound",
        "recovery adaptation cycle",
        "stimulus recovery adaptation",
    ),
    "detraining": (
        "detraining",
        "training cessation",
        "training interruption",
        "loss of fitness",
        "deconditioning",
        "reversibility",
    ),
    # -------------------------------------------------------------------------
    # TRAINING LOAD AND MONITORING
    # -------------------------------------------------------------------------
    "training_load": (
        "training load",
        "exercise load",
        "workload",
        "training stress",
        "external load",
        "internal load",
        "session load",
        "training dose",
    ),
    "external_load": (
        "external load",
        "external workload",
        "mechanical load",
        "distance",
        "power output",
        "speed",
        "accelerations",
        "training volume",
    ),
    "internal_load": (
        "internal load",
        "internal training load",
        "physiological load",
        "heart rate load",
        "rpe load",
        "session rpe",
        "trimp",
        "training impulse",
    ),
    "trimp": (
        "trimp",
        "training impulse",
        "heart rate training load",
        "banister trimp",
        "edwards trimp",
        "lucia trimp",
        "internal load",
    ),
    "tss": (
        "tss",
        "training stress score",
        "training stress",
        "cycling training load",
        "normalized power stress",
    ),
    "normalized_power": (
        "normalized power",
        "normalised power",
        "np",
        "weighted power",
        "physiological power",
    ),
    "intensity_factor": (
        "intensity factor",
        "if",
        "relative intensity",
        "normalized power divided by ftp",
        "np to ftp ratio",
    ),
    "acute_training_load": (
        "acute training load",
        "atl",
        "acute workload",
        "fatigue load",
        "short term training load",
        "short-term training load",
    ),
    "chronic_training_load": (
        "chronic training load",
        "ctl",
        "chronic workload",
        "fitness load",
        "long term training load",
        "long-term training load",
    ),
    "training_stress_balance": (
        "training stress balance",
        "tsb",
        "form",
        "freshness",
        "fitness fatigue balance",
        "performance management chart",
    ),
    "acute_chronic_workload_ratio": (
        "acute chronic workload ratio",
        "acute:chronic workload ratio",
        "acwr",
        "workload ratio",
        "acute to chronic load",
    ),
    "session_rpe": (
        "session rpe",
        "s-rpe",
        "srpe",
        "session rating of perceived exertion",
        "rpe training load",
        "duration times rpe",
    ),
    "monotony": (
        "training monotony",
        "monotony",
        "load monotony",
        "day to day load variation",
        "training variability",
    ),
    "training_strain": (
        "training strain",
        "strain",
        "weekly strain",
        "training load strain",
        "monotony times load",
    ),
    # -------------------------------------------------------------------------
    # PERCEIVED EFFORT AND AUTOREGULATION
    # -------------------------------------------------------------------------
    "rpe": (
        "rpe",
        "rating of perceived exertion",
        "ratings of perceived exertion",
        "perceived exertion",
        "perceived effort",
        "borg scale",
        "borg rpe",
        "session rpe",
        "effort rating",
    ),
    "rir": (
        "rir",
        "repetitions in reserve",
        "reps in reserve",
        "repetition reserve",
        "proximity to failure",
        "reps before failure",
    ),
    "autoregulation": (
        "autoregulation",
        "auto regulation",
        "autoregulated training",
        "readiness based training",
        "rpe based training",
        "rir based training",
        "velocity based training",
        "daily load adjustment",
    ),
    # -------------------------------------------------------------------------
    # CARDIOVASCULAR PHYSIOLOGY
    # -------------------------------------------------------------------------
    "cardiac": (
        "cardiac",
        "cardiovascular",
        "heart",
        "cardiac function",
        "heart function",
        "cardiac adaptation",
        "cardiovascular adaptation",
    ),
    "cardiac_output": (
        "cardiac output",
        "q",
        "q dot",
        "q̇",
        "heart output",
        "stroke volume times heart rate",
        "blood flow",
        "systemic blood flow",
    ),
    "stroke_volume": (
        "stroke volume",
        "sv",
        "cardiac stroke volume",
        "blood per beat",
        "ventricular ejection volume",
        "end diastolic volume",
        "preload",
        "venous return",
    ),
    "heart_rate": (
        "heart rate",
        "hr",
        "pulse",
        "cardiac frequency",
        "beats per minute",
        "bpm",
    ),
    "heart_rate_max": (
        "heart rate max",
        "maximum heart rate",
        "maximal heart rate",
        "hrmax",
        "hr max",
        "max hr",
        "peak heart rate",
    ),
    "heart_rate_reserve": (
        "heart rate reserve",
        "hrr",
        "karvonen",
        "karvonen method",
        "maximum heart rate minus resting heart rate",
    ),
    "resting_heart_rate": (
        "resting heart rate",
        "resting hr",
        "rhr",
        "morning heart rate",
        "baseline heart rate",
        "resting pulse",
    ),
    "heart_rate_recovery": (
        "heart rate recovery",
        "hrr",
        "post exercise heart rate recovery",
        "heart rate decay",
        "one minute heart rate recovery",
        "parasympathetic reactivation",
    ),
    "heart_rate_variability": (
        "heart rate variability",
        "hrv",
        "r r variability",
        "rr variability",
        "r-r intervals",
        "rmssd",
        "sdnn",
        "parasympathetic activity",
        "autonomic nervous system",
        "cardiac autonomic regulation",
        "autonomic recovery",
    ),
    "hrv": (
        "hrv",
        "heart rate variability",
        "rmssd",
        "sdnn",
        "r-r intervals",
        "autonomic recovery",
        "parasympathetic tone",
    ),
    "cardiac_hypertrophy": (
        "cardiac hypertrophy",
        "athlete's heart",
        "athletes heart",
        "physiological cardiac hypertrophy",
        "left ventricular hypertrophy",
        "eccentric cardiac hypertrophy",
        "concentric cardiac hypertrophy",
        "cardiac remodeling",
        "cardiac remodelling",
    ),
    "end_diastolic_volume": (
        "end diastolic volume",
        "end-diastolic volume",
        "edv",
        "ventricular filling",
        "preload",
        "cardiac filling",
    ),
    "ejection_fraction": (
        "ejection fraction",
        "ef",
        "ventricular ejection fraction",
        "left ventricular ejection fraction",
        "lvef",
    ),
    "blood_pressure": (
        "blood pressure",
        "bp",
        "arterial pressure",
        "systolic blood pressure",
        "diastolic blood pressure",
        "mean arterial pressure",
        "map",
    ),
    "plasma_volume": (
        "plasma volume",
        "blood plasma volume",
        "plasma volume expansion",
        "hypervolemia",
        "haemodilution",
        "hemodilution",
        "blood volume expansion",
    ),
    "blood_volume": (
        "blood volume",
        "total blood volume",
        "circulating blood volume",
        "plasma volume",
        "red cell volume",
        "erythrocyte volume",
    ),
    "arteriovenous_oxygen_difference": (
        "arteriovenous oxygen difference",
        "arterial venous oxygen difference",
        "a-v o2 difference",
        "av o2 difference",
        "avdo2",
        "oxygen extraction",
        "peripheral oxygen extraction",
    ),
    "fick_equation": (
        "fick equation",
        "fick principle",
        "cardiac output times av o2 difference",
        "vo2 equals q times avdo2",
        "oxygen uptake equation",
    ),
    # -------------------------------------------------------------------------
    # RESPIRATORY PHYSIOLOGY
    # -------------------------------------------------------------------------
    "ventilation": (
        "ventilation",
        "minute ventilation",
        "ve",
        "v̇e",
        "pulmonary ventilation",
        "breathing rate",
        "ventilatory response",
    ),
    "respiratory_exchange_ratio": (
        "respiratory exchange ratio",
        "rer",
        "vco2 vo2 ratio",
        "carbon dioxide to oxygen ratio",
        "substrate utilization",
        "substrate utilisation",
    ),
    "ventilatory_equivalent": (
        "ventilatory equivalent",
        "ve vo2",
        "ve vco2",
        "ventilatory efficiency",
        "oxygen ventilatory equivalent",
        "carbon dioxide ventilatory equivalent",
    ),
    "breathing_frequency": (
        "breathing frequency",
        "respiratory frequency",
        "respiratory rate",
        "breathing rate",
        "respirations per minute",
    ),
    "tidal_volume": (
        "tidal volume",
        "vt",
        "breath volume",
        "inspiratory volume",
        "volume per breath",
    ),
    "respiratory_muscle_training": (
        "respiratory muscle training",
        "inspiratory muscle training",
        "imt",
        "breathing muscle training",
        "respiratory strength training",
        "inspiratory resistance training",
    ),
    # -------------------------------------------------------------------------
    # MUSCLE OXYGENATION AND PERIPHERAL ADAPTATIONS
    # -------------------------------------------------------------------------
    "muscle_oxygenation": (
        "muscle oxygenation",
        "muscle oxygen saturation",
        "smo2",
        "tissue saturation index",
        "tsi",
        "near infrared spectroscopy",
        "nirs",
        "muscle o2",
    ),
    "oxygen_delivery": (
        "oxygen delivery",
        "o2 delivery",
        "systemic oxygen delivery",
        "muscle oxygen delivery",
        "blood flow",
        "cardiac output",
        "haemoglobin",
        "hemoglobin",
    ),
    "oxygen_extraction": (
        "oxygen extraction",
        "peripheral oxygen extraction",
        "muscle oxygen extraction",
        "arteriovenous oxygen difference",
        "avdo2",
        "fractional oxygen extraction",
    ),
    "capillarization": (
        "capillarization",
        "capillarisation",
        "capillary density",
        "capillary supply",
        "capillary to fiber ratio",
        "capillary to fibre ratio",
        "angiogenesis",
        "muscle microvasculature",
    ),
    "mitochondria": (
        "mitochondria",
        "mitochondrial",
        "mitochondrial density",
        "mitochondrial content",
        "mitochondrial volume",
        "mitochondrial biogenesis",
        "oxidative machinery",
    ),
    "mitochondrial_biogenesis": (
        "mitochondrial biogenesis",
        "mitochondrial adaptation",
        "mitochondrial proliferation",
        "pgc-1alpha",
        "pgc1a",
        "pgc-1α",
        "ampk",
        "p38 mapk",
        "oxidative adaptation",
    ),
    "oxidative_capacity": (
        "oxidative capacity",
        "muscle oxidative capacity",
        "aerobic enzyme activity",
        "mitochondrial capacity",
        "oxidative enzyme activity",
        "citrate synthase",
        "succinate dehydrogenase",
    ),
    "fiber_type": (
        "fiber type",
        "fibre type",
        "muscle fiber type",
        "muscle fibre type",
        "type i fiber",
        "type ii fiber",
        "slow twitch",
        "fast twitch",
        "myosin heavy chain",
        "mhc",
    ),
    "type_i_fiber": (
        "type i fiber",
        "type 1 fiber",
        "type i fibre",
        "slow twitch",
        "slow oxidative fiber",
        "oxidative fiber",
        "red fiber",
    ),
    "type_ii_fiber": (
        "type ii fiber",
        "type 2 fiber",
        "type ii fibre",
        "fast twitch",
        "fast glycolytic fiber",
        "type iia",
        "type iix",
        "type iib",
    ),
    # -------------------------------------------------------------------------
    # LACTATE, ACID-BASE BALANCE, AND METABOLISM
    # -------------------------------------------------------------------------
    "lactate": (
        "lactate",
        "blood lactate",
        "muscle lactate",
        "lactic acid",
        "lactatemia",
        "blood lactate concentration",
        "bLa",
        "lactate accumulation",
        "lactate production",
        "lactate clearance",
    ),
    "lactate_shuttle": (
        "lactate shuttle",
        "cell to cell lactate shuttle",
        "intracellular lactate shuttle",
        "lactate transport",
        "lactate oxidation",
        "lactate clearance",
        "mct1",
        "mct4",
        "monocarboxylate transporter",
    ),
    "lactate_clearance": (
        "lactate clearance",
        "lactate removal",
        "lactate elimination",
        "lactate oxidation",
        "lactate disposal",
        "lactate recovery",
    ),
    "buffering_capacity": (
        "buffering capacity",
        "buffer capacity",
        "acid buffering",
        "hydrogen ion buffering",
        "intracellular buffering",
        "extracellular buffering",
        "acid base regulation",
        "acid-base regulation",
    ),
    "metabolic_acidosis": (
        "metabolic acidosis",
        "exercise induced acidosis",
        "exercise-induced acidosis",
        "hydrogen ion accumulation",
        "h+ accumulation",
        "ph decline",
        "muscle acidosis",
    ),
    "glycolysis": (
        "glycolysis",
        "glycolytic metabolism",
        "anaerobic glycolysis",
        "aerobic glycolysis",
        "glucose breakdown",
        "glycolytic pathway",
    ),
    "oxidative_phosphorylation": (
        "oxidative phosphorylation",
        "oxphos",
        "aerobic metabolism",
        "mitochondrial respiration",
        "electron transport chain",
        "atp synthesis",
    ),
    "phosphagen_system": (
        "phosphagen system",
        "atp pc system",
        "atp-pc system",
        "atp pcr system",
        "phosphocreatine system",
        "creatine phosphate system",
        "alactic system",
        "immediate energy system",
    ),
    "fat_oxidation": (
        "fat oxidation",
        "fat burning",
        "lipid oxidation",
        "fat metabolism",
        "beta oxidation",
        "β-oxidation",
        "free fatty acid oxidation",
    ),
    "fatmax": (
        "fatmax",
        "fat max",
        "maximal fat oxidation",
        "maximum fat oxidation",
        "mfo",
        "peak fat oxidation",
        "fat oxidation zone",
    ),
    "carbohydrate_oxidation": (
        "carbohydrate oxidation",
        "carb oxidation",
        "cho oxidation",
        "glucose oxidation",
        "glycogen oxidation",
        "carbohydrate metabolism",
    ),
    "metabolic_flexibility": (
        "metabolic flexibility",
        "substrate flexibility",
        "fuel flexibility",
        "fuel switching",
        "substrate switching",
        "fat carbohydrate crossover",
    ),
    # -------------------------------------------------------------------------
    # STRENGTH QUALITIES
    # -------------------------------------------------------------------------
    "maximal_strength": (
        "maximal strength",
        "maximum strength",
        "max strength",
        "absolute strength",
        "peak strength",
        "one repetition maximum",
        "1rm",
        "one rep max",
        "maximal voluntary force",
    ),
    "relative_strength": (
        "relative strength",
        "strength to body mass ratio",
        "strength to weight ratio",
        "body mass normalized strength",
        "body mass normalised strength",
        "allometric strength",
    ),
    "muscular_endurance": (
        "muscular endurance",
        "strength endurance",
        "local muscular endurance",
        "local muscle endurance",
        "repetition endurance",
        "fatigue resistance",
        "repetitions to failure",
    ),
    "power": (
        "power",
        "muscular power",
        "mechanical power",
        "explosive power",
        "power output",
        "force velocity power",
        "force times velocity",
        "work rate",
    ),
    "peak_power": (
        "peak power",
        "maximum power",
        "maximal power",
        "instantaneous power",
        "sprint power",
        "explosive power",
        "wingate peak power",
    ),
    "explosive_strength": (
        "explosive strength",
        "explosive power",
        "rapid force production",
        "ballistic strength",
        "starting strength",
        "rate of force development",
        "rfd",
    ),
    "rate_of_force_development": (
        "rate of force development",
        "rfd",
        "rate of force production",
        "force rise",
        "explosive strength",
        "early phase force",
        "rapid force production",
    ),
    "strength_deficit": (
        "strength deficit",
        "explosive strength deficit",
        "dynamic strength deficit",
        "force deficit",
        "maximum strength deficit",
    ),
    "isometric_strength": (
        "isometric strength",
        "static strength",
        "isometric force",
        "maximal voluntary isometric contraction",
        "mvic",
        "maximum voluntary contraction",
        "mvc",
    ),
    "dynamic_strength": (
        "dynamic strength",
        "isotonic strength",
        "concentric strength",
        "eccentric strength",
        "dynamic force",
        "movement strength",
    ),
    "grip_strength": (
        "grip strength",
        "handgrip strength",
        "hand grip strength",
        "grip force",
        "hand dynamometry",
    ),
    # -------------------------------------------------------------------------
    # HYPERTROPHY AND MUSCLE MORPHOLOGY
    # -------------------------------------------------------------------------
    "skeletal_muscle_hypertrophy": (
        "skeletal muscle hypertrophy",
        "muscle hypertrophy",
        "hypertrophy",
        "muscle growth",
        "muscle size",
        "muscle mass gain",
        "fiber hypertrophy",
        "fibre hypertrophy",
        "myofibrillar hypertrophy",
    ),
    "muscle_cross_sectional_area": (
        "muscle cross sectional area",
        "muscle cross-sectional area",
        "cross sectional area",
        "cross-sectional area",
        "csa",
        "physiological cross sectional area",
        "pcsa",
        "muscle size",
    ),
    "fascicle_length": (
        "fascicle length",
        "muscle fascicle length",
        "fiber length",
        "fibre length",
        "sarcomeres in series",
        "muscle architecture",
    ),
    "pennation_angle": (
        "pennation angle",
        "muscle pennation",
        "fascicle pennation",
        "fiber pennation",
        "fibre pennation",
        "muscle architecture",
    ),
    "muscle_architecture": (
        "muscle architecture",
        "fascicle length",
        "pennation angle",
        "muscle thickness",
        "cross sectional area",
        "muscle volume",
    ),
    # -------------------------------------------------------------------------
    # RESISTANCE-TRAINING METHODS
    # -------------------------------------------------------------------------
    "hypertrophy_training": (
        "hypertrophy training",
        "bodybuilding training",
        "muscle growth training",
        "high volume resistance training",
        "moderate load resistance training",
        "mass training",
    ),
    "power_training": (
        "power training",
        "explosive training",
        "ballistic training",
        "speed strength training",
        "dynamic effort training",
        "velocity training",
    ),
    "plyometric_training": (
        "plyometric training",
        "plyometrics",
        "jump training",
        "reactive strength training",
        "shock training",
        "stretch shortening cycle training",
        "depth jumps",
        "bounding",
        "hopping",
    ),
    "eccentric_training": (
        "eccentric training",
        "eccentric exercise",
        "eccentric overload",
        "negative training",
        "lengthening contraction",
        "accentuated eccentric loading",
        "flywheel training",
    ),
    "concentric_training": (
        "concentric training",
        "concentric exercise",
        "shortening contraction",
        "positive phase training",
        "concentric only training",
    ),
    "isometric_training": (
        "isometric training",
        "static training",
        "isometric exercise",
        "static contraction",
        "yielding isometric",
        "overcoming isometric",
        "isometric hold",
    ),
    "isokinetic_training": (
        "isokinetic training",
        "isokinetic exercise",
        "constant velocity resistance",
        "dynamometer training",
        "isokinetic dynamometry",
    ),
    "velocity_based_training": (
        "velocity based training",
        "velocity-based training",
        "vbt",
        "bar velocity training",
        "movement velocity",
        "velocity loss",
        "load velocity profile",
        "load-velocity profile",
        "velocity monitoring",
    ),
    "blood_flow_restriction": (
        "blood flow restriction",
        "blood flow restriction training",
        "bfr",
        "bfr training",
        "occlusion training",
        "kaatsu",
        "low load bfr",
        "vascular occlusion training",
    ),
    "flywheel_training": (
        "flywheel training",
        "iso inertial training",
        "isoinertial training",
        "inertial resistance training",
        "eccentric overload",
        "flywheel resistance exercise",
    ),
    "circuit_training": (
        "circuit training",
        "resistance circuit",
        "strength circuit",
        "metabolic resistance training",
        "station training",
        "circuit resistance training",
    ),
    "complex_training": (
        "complex training",
        "contrast training",
        "strength power complex",
        "heavy light training",
        "post activation performance enhancement",
        "pape",
        "post activation potentiation",
        "pap",
    ),
    "cluster_sets": (
        "cluster sets",
        "cluster training",
        "intra set rest",
        "intraset rest",
        "rest redistribution",
        "inter repetition rest",
        "inter-repetition rest",
    ),
    "drop_sets": (
        "drop sets",
        "descending sets",
        "strip sets",
        "breakdown sets",
        "load reduction sets",
    ),
    "supersets": (
        "supersets",
        "super sets",
        "paired sets",
        "agonist antagonist sets",
        "compound sets",
        "pre exhaustion",
        "pre-exhaustion",
    ),
    # -------------------------------------------------------------------------
    # STRENGTH EXERCISE CLASSIFICATION
    # -------------------------------------------------------------------------
    "unilateral": (
        "unilateral",
        "single leg",
        "single-leg",
        "one leg",
        "one-leg",
        "single arm",
        "single-arm",
        "one sided",
        "one-sided",
        "split stance",
        "asymmetrical",
        "unilateral training",
    ),
    "bilateral": (
        "bilateral",
        "double leg",
        "double-leg",
        "two leg",
        "two-leg",
        "two arm",
        "two-arm",
        "both limbs",
        "symmetrical",
        "bilateral training",
    ),
    "bilateral_deficit": (
        "bilateral deficit",
        "bilateral force deficit",
        "bilateral strength deficit",
        "bilateral facilitation",
        "bilateral index",
        "bilateral limb deficit",
    ),
    "compound_exercise": (
        "compound exercise",
        "compound lift",
        "multi joint exercise",
        "multi-joint exercise",
        "closed chain exercise",
        "structural exercise",
        "basic lift",
    ),
    "isolation_exercise": (
        "isolation exercise",
        "single joint exercise",
        "single-joint exercise",
        "isolated exercise",
        "accessory exercise",
    ),
    "free_weights": (
        "free weights",
        "free weight training",
        "barbell training",
        "dumbbell training",
        "kettlebell training",
        "unconstrained resistance",
    ),
    "machine_training": (
        "machine training",
        "resistance machines",
        "weight machines",
        "selectorized machine",
        "plate loaded machine",
        "guided resistance",
    ),
    "closed_kinetic_chain": (
        "closed kinetic chain",
        "closed chain",
        "ckc",
        "closed kinetic chain exercise",
        "weight bearing exercise",
    ),
    "open_kinetic_chain": (
        "open kinetic chain",
        "open chain",
        "okc",
        "open kinetic chain exercise",
        "non weight bearing exercise",
    ),
    # -------------------------------------------------------------------------
    # COMMON LIFTS AND MOVEMENT PATTERNS
    # -------------------------------------------------------------------------
    "squat": (
        "squat",
        "back squat",
        "front squat",
        "barbell squat",
        "goblet squat",
        "box squat",
        "split squat",
        "leg press",
        "knee dominant exercise",
    ),
    "deadlift": (
        "deadlift",
        "conventional deadlift",
        "sumo deadlift",
        "trap bar deadlift",
        "hex bar deadlift",
        "romanian deadlift",
        "rdl",
        "hip hinge",
    ),
    "bench_press": (
        "bench press",
        "barbell bench press",
        "dumbbell bench press",
        "chest press",
        "horizontal press",
        "upper body push",
    ),
    "overhead_press": (
        "overhead press",
        "shoulder press",
        "military press",
        "vertical press",
        "upper body press",
    ),
    "pull_up": (
        "pull up",
        "pull-up",
        "pullup",
        "chin up",
        "chin-up",
        "vertical pull",
        "lat pull down",
        "lat pulldown",
    ),
    "rowing_exercise": (
        "row exercise",
        "rowing exercise",
        "barbell row",
        "dumbbell row",
        "seated row",
        "horizontal pull",
    ),
    "hip_thrust": (
        "hip thrust",
        "barbell hip thrust",
        "glute bridge",
        "hip extension exercise",
        "horizontal hip extension",
    ),
    "calf_raise": (
        "calf raise",
        "heel raise",
        "plantar flexion exercise",
        "soleus raise",
        "gastrocnemius raise",
        "calf strengthening",
    ),
    # -------------------------------------------------------------------------
    # RESISTANCE-TRAINING VARIABLES
    # -------------------------------------------------------------------------
    "one_rep_max": (
        "1rm",
        "one rep max",
        "one repetition maximum",
        "one-repetition maximum",
        "1 repetition maximum",
        "maximal dynamic strength",
        "maximum lift",
    ),
    "repetition_maximum": (
        "repetition maximum",
        "rm",
        "rep max",
        "repetition max",
        "multiple repetition maximum",
        "3rm",
        "5rm",
        "10rm",
    ),
    "training_volume": (
        "training volume",
        "exercise volume",
        "workout volume",
        "set volume",
        "repetition volume",
        "volume load",
        "tonnage",
        "sets times reps",
    ),
    "volume_load": (
        "volume load",
        "volume-load",
        "sets reps load",
        "sets times reps times load",
        "tonnage",
        "total weight lifted",
        "training volume",
    ),
    "training_frequency": (
        "training frequency",
        "exercise frequency",
        "session frequency",
        "weekly frequency",
        "sessions per week",
        "training days",
    ),
    "set": (
        "set",
        "sets",
        "exercise set",
        "working set",
        "work set",
        "training set",
    ),
    "repetition": (
        "repetition",
        "repetitions",
        "rep",
        "reps",
        "movement repetition",
    ),
    "rest_interval": (
        "rest interval",
        "inter set rest",
        "inter-set rest",
        "rest period",
        "recovery interval",
        "between set recovery",
    ),
    "tempo": (
        "lifting tempo",
        "repetition tempo",
        "movement tempo",
        "eccentric duration",
        "concentric duration",
        "time under tension",
        "tut",
    ),
    "time_under_tension": (
        "time under tension",
        "tut",
        "repetition duration",
        "set duration",
        "muscle tension duration",
        "lifting tempo",
    ),
    "range_of_motion": (
        "range of motion",
        "rom",
        "full range of motion",
        "partial range of motion",
        "movement amplitude",
        "joint excursion",
    ),
    "training_to_failure": (
        "training to failure",
        "failure training",
        "momentary muscular failure",
        "muscular failure",
        "repetition failure",
        "task failure",
        "volitional failure",
    ),
    "proximity_to_failure": (
        "proximity to failure",
        "repetitions in reserve",
        "rir",
        "reps in reserve",
        "velocity loss",
        "distance from failure",
    ),
    # -------------------------------------------------------------------------
    # FORCE-VELOCITY AND NEUROMUSCULAR PERFORMANCE
    # -------------------------------------------------------------------------
    "force_velocity": (
        "force velocity",
        "force-velocity",
        "force velocity relationship",
        "force velocity profile",
        "fv profile",
        "load velocity relationship",
        "strength speed continuum",
    ),
    "force_velocity_profile": (
        "force velocity profile",
        "force-velocity profile",
        "fv profile",
        "force deficit",
        "velocity deficit",
        "optimal profile",
        "horizontal force velocity profile",
        "vertical force velocity profile",
    ),
    "load_velocity_profile": (
        "load velocity profile",
        "load-velocity profile",
        "lvp",
        "bar velocity profile",
        "velocity load relationship",
        "velocity based training",
    ),
    "motor_unit": (
        "motor unit",
        "motor units",
        "motor neuron",
        "motor neurone",
        "muscle fibers innervated",
        "neuromuscular unit",
    ),
    "motor_unit_recruitment": (
        "motor unit recruitment",
        "muscle recruitment",
        "motor unit activation",
        "size principle",
        "neural recruitment",
    ),
    "rate_coding": (
        "rate coding",
        "motor unit firing rate",
        "motor unit discharge rate",
        "firing frequency",
        "frequency coding",
    ),
    "neural_adaptation": (
        "neural adaptation",
        "neural adaptations",
        "neuromuscular adaptation",
        "motor unit recruitment",
        "rate coding",
        "intermuscular coordination",
        "intramuscular coordination",
        "neural drive",
    ),
    "neuromuscular_efficiency": (
        "neuromuscular efficiency",
        "neuromuscular economy",
        "neural efficiency",
        "emg force ratio",
        "muscle activation efficiency",
    ),
    "electromyography": (
        "electromyography",
        "emg",
        "surface emg",
        "semg",
        "muscle activation",
        "electrical muscle activity",
        "normalized emg",
    ),
    "stretch_shortening_cycle": (
        "stretch shortening cycle",
        "stretch-shortening cycle",
        "ssc",
        "eccentric concentric coupling",
        "elastic energy",
        "reactive strength",
        "plyometric action",
    ),
    "reactive_strength": (
        "reactive strength",
        "reactive strength index",
        "rsi",
        "stretch shortening cycle",
        "plyometric ability",
        "jump reactivity",
        "contact time jump height ratio",
    ),
    # -------------------------------------------------------------------------
    # TENDON, CONNECTIVE TISSUE, AND ELASTICITY
    # -------------------------------------------------------------------------
    "tendon_stiffness": (
        "tendon stiffness",
        "tendon mechanical properties",
        "tendon compliance",
        "series elastic stiffness",
        "muscle tendon stiffness",
        "elastic stiffness",
    ),
    "musculotendinous_stiffness": (
        "musculotendinous stiffness",
        "muscle tendon stiffness",
        "muscle-tendon stiffness",
        "mtu stiffness",
        "leg stiffness",
        "vertical stiffness",
    ),
    "tendon_adaptation": (
        "tendon adaptation",
        "tendon remodeling",
        "tendon remodelling",
        "tendon hypertrophy",
        "tendon stiffness adaptation",
        "connective tissue adaptation",
    ),
    # -------------------------------------------------------------------------
    # CONCURRENT STRENGTH AND ENDURANCE TRAINING
    # -------------------------------------------------------------------------
    "concurrent_training": (
        "concurrent training",
        "combined training",
        "concurrent strength and endurance training",
        "strength endurance training",
        "endurance and resistance training",
        "aerobic and resistance training",
        "hybrid training",
        "multimodal training",
    ),
    "interference_effect": (
        "interference effect",
        "concurrent training interference",
        "strength endurance interference",
        "molecular interference",
        "adaptation interference",
        "ampk mtor interference",
        "endurance strength conflict",
    ),
    "strength_for_endurance": (
        "strength for endurance",
        "strength training for endurance",
        "resistance training for endurance athletes",
        "heavy strength training",
        "maximal strength training",
        "endurance strength training",
        "running strength training",
        "cycling strength training",
    ),
    "heavy_strength_training": (
        "heavy strength training",
        "heavy resistance training",
        "high load strength training",
        "maximal strength training",
        "low repetition strength training",
        "heavy lifting",
    ),
    "strength_endurance": (
        "strength endurance",
        "muscular endurance",
        "local muscular endurance",
        "resistance to fatigue",
        "repetition endurance",
        "force endurance",
    ),
    # -------------------------------------------------------------------------
    # FATIGUE AND RECOVERY
    # -------------------------------------------------------------------------
    "fatigue": (
        "fatigue",
        "exercise fatigue",
        "performance fatigability",
        "perceived fatigability",
        "neuromuscular fatigue",
        "central fatigue",
        "peripheral fatigue",
        "muscle fatigue",
        "task failure",
    ),
    "central_fatigue": (
        "central fatigue",
        "central nervous system fatigue",
        "cns fatigue",
        "reduced central drive",
        "supraspinal fatigue",
        "voluntary activation failure",
    ),
    "peripheral_fatigue": (
        "peripheral fatigue",
        "muscle fatigue",
        "contractile fatigue",
        "peripheral neuromuscular fatigue",
        "excitation contraction failure",
        "metabolic fatigue",
    ),
    "neuromuscular_fatigue": (
        "neuromuscular fatigue",
        "nmf",
        "central fatigue",
        "peripheral fatigue",
        "force loss",
        "voluntary activation loss",
        "contractile impairment",
    ),
    "recovery": (
        "recovery",
        "exercise recovery",
        "post exercise recovery",
        "training recovery",
        "regeneration",
        "restoration",
        "readiness restoration",
    ),
    "active_recovery": (
        "active recovery",
        "active cool down",
        "active cooldown",
        "recovery exercise",
        "low intensity recovery",
        "recovery ride",
        "recovery run",
    ),
    "passive_recovery": (
        "passive recovery",
        "complete rest",
        "rest recovery",
        "seated recovery",
        "stationary recovery",
    ),
    "readiness": (
        "readiness",
        "training readiness",
        "athlete readiness",
        "recovery status",
        "preparedness",
        "daily readiness",
        "wellness",
        "freshness",
    ),
    "overreaching": (
        "overreaching",
        "functional overreaching",
        "for",
        "nonfunctional overreaching",
        "nfor",
        "training overload",
        "short term performance decrement",
    ),
    "overtraining": (
        "overtraining",
        "overtraining syndrome",
        "ots",
        "maladaptation",
        "chronic fatigue",
        "underperformance syndrome",
        "unexplained underperformance",
        "burnout",
    ),
    "doms": (
        "doms",
        "delayed onset muscle soreness",
        "muscle soreness",
        "post exercise soreness",
        "post-exercise soreness",
        "exercise induced muscle damage",
    ),
    "exercise_induced_muscle_damage": (
        "exercise induced muscle damage",
        "exercise-induced muscle damage",
        "eimd",
        "muscle damage",
        "eccentric muscle damage",
        "creatine kinase",
        "ck",
        "doms",
    ),
    "sleep": (
        "sleep",
        "sleep quality",
        "sleep duration",
        "sleep efficiency",
        "sleep deprivation",
        "sleep restriction",
        "sleep extension",
        "athlete sleep",
        "recovery sleep",
    ),
    # -------------------------------------------------------------------------
    # NUTRITION AND FUELING
    # -------------------------------------------------------------------------
    "carbohydrate": (
        "carbohydrate",
        "carbohydrates",
        "carbs",
        "cho",
        "glucose",
        "maltodextrin",
        "fructose",
        "sports drink",
        "carbohydrate intake",
        "carbohydrate feeding",
    ),
    "carbohydrate_loading": (
        "carbohydrate loading",
        "carb loading",
        "glycogen loading",
        "carbo loading",
        "supercompensation diet",
        "pre race carbohydrate",
    ),
    "glycogen": (
        "glycogen",
        "muscle glycogen",
        "liver glycogen",
        "glycogen storage",
        "glycogen depletion",
        "glycogen resynthesis",
        "carbohydrate stores",
    ),
    "low_carbohydrate_availability": (
        "low carbohydrate availability",
        "low carbohydrate training",
        "low carb training",
        "train low",
        "glycogen depleted training",
        "sleep low",
        "fasted training",
    ),
    "protein": (
        "protein",
        "dietary protein",
        "protein intake",
        "amino acids",
        "essential amino acids",
        "eaa",
        "whey protein",
        "muscle protein synthesis",
        "mps",
    ),
    "ergogenic_aids": (
        "ergogenic aids",
        "ergogenic aid",
        "ergogenic supplements",
        "ergogenic supplement",
        "ergogenic substances",
        "creatine",
        "caffeine",
        "nitrate",
        "bicarbonate",
        "sodium bicarbonate",
        "beta-alanine",
        "performance supplements",
    ),
    "ergogenic_aid": (
        "ergogenic aid",
        "ergogenic aids",
        "ergogenic supplement",
        "creatine",
        "caffeine",
        "nitrate",
        "bicarbonate",
    ),
    "creatine": (
        "creatine",
        "creatine monohydrate",
        "creatine supplementation",
        "phosphocreatine",
        "pcr",
        "creatine loading",
        "phosphagen system",
    ),
    "bicarbonate": (
        "sodium bicarbonate",
        "bicarbonate",
        "nahco3",
        "bicarb",
        "bicarbonate supplementation",
        "extracellular buffering",
        "buffering agent",
        "alkalosis",
    ),
    "beta_alanine": (
        "beta alanine",
        "beta-alanine",
        "β-alanine",
        "carnosine",
        "muscle carnosine",
        "intracellular buffering",
        "buffering supplement",
    ),
    "caffeine": (
        "caffeine",
        "caffeine supplementation",
        "coffee",
        "ergogenic caffeine",
        "central stimulant",
        "adenosine antagonist",
        "pre workout caffeine",
    ),
    "dietary_nitrate": (
        "dietary nitrate",
        "nitrate",
        "beetroot juice",
        "beet juice",
        "nitric oxide",
        "no3",
        "nitrite",
        "nitrate supplementation",
    ),
    "iron": (
        "iron",
        "iron status",
        "iron deficiency",
        "ferritin",
        "haemoglobin",
        "hemoglobin",
        "transferrin saturation",
        "iron supplementation",
        "sports anemia",
        "sports anaemia",
    ),
    "hydration": (
        "hydration",
        "fluid intake",
        "fluid replacement",
        "rehydration",
        "dehydration",
        "fluid balance",
        "body water",
        "sports hydration",
    ),
    "electrolytes": (
        "electrolytes",
        "sodium",
        "potassium",
        "magnesium",
        "chloride",
        "electrolyte replacement",
        "sports drink",
        "oral rehydration",
    ),
    "energy_availability": (
        "energy availability",
        "low energy availability",
        "lea",
        "caloric availability",
        "energy deficiency",
        "relative energy deficiency",
        "red-s",
    ),
    "reds": (
        "red-s",
        "reds",
        "relative energy deficiency in sport",
        "relative energy deficiency",
        "low energy availability",
        "lea",
        "female athlete triad",
        "male athlete triad",
    ),
    "underfueling": (
        "underfueling",
        "under-fueling",
        "chronic underfueling",
        "low energy availability",
        "lea",
        "relative energy deficiency",
        "relative energy deficiency in sport",
        "red-s",
        "reds",
        "energy deficit",
    ),
    "underfueling_reds": (
        "underfueling",
        "under-fueling",
        "red-s",
        "reds",
        "relative energy deficiency",
        "relative energy deficiency in sport",
        "low energy availability",
        "lea",
        "chronic underfueling",
    ),
    # -------------------------------------------------------------------------
    # THERMOREGULATION AND ENVIRONMENT
    # -------------------------------------------------------------------------
    "heat_training": (
        "heat training",
        "heat acclimation",
        "heat acclimatization",
        "heat acclimatisation",
        "heat adaptation",
        "thermal training",
        "hot environment training",
    ),
    "heat_acclimation": (
        "heat acclimation",
        "heat acclimatization",
        "heat acclimatisation",
        "heat adaptation",
        "thermal acclimation",
        "passive heat acclimation",
        "active heat acclimation",
    ),
    "core_temperature": (
        "core temperature",
        "core body temperature",
        "body temperature",
        "rectal temperature",
        "gastrointestinal temperature",
        "thermal strain",
    ),
    "sweat_rate": (
        "sweat rate",
        "sweating rate",
        "whole body sweat rate",
        "sweat loss",
        "fluid loss",
        "perspiration rate",
    ),
    "altitude_training": (
        "altitude training",
        "hypoxic training",
        "hypoxia training",
        "high altitude training",
        "live high train low",
        "lhtl",
        "live high train high",
        "intermittent hypoxic training",
    ),
    "hypoxia": (
        "hypoxia",
        "hypoxic exposure",
        "normobaric hypoxia",
        "hypobaric hypoxia",
        "reduced oxygen",
        "low oxygen",
        "altitude exposure",
    ),
    "altitude_acclimatization": (
        "altitude acclimatization",
        "altitude acclimatisation",
        "altitude adaptation",
        "hypoxic adaptation",
        "acclimation to altitude",
        "erythropoietic adaptation",
    ),
    "hemoglobin_mass": (
        "hemoglobin mass",
        "haemoglobin mass",
        "hbmass",
        "total hemoglobin mass",
        "total haemoglobin mass",
        "red cell mass",
        "oxygen carrying capacity",
    ),
    "erythropoietin": (
        "erythropoietin",
        "epo",
        "endogenous epo",
        "erythropoiesis",
        "red blood cell production",
        "altitude response",
    ),
    # -------------------------------------------------------------------------
    # TESTING
    # -------------------------------------------------------------------------
    "cardiopulmonary_exercise_test": (
        "cardiopulmonary exercise test",
        "cardiopulmonary exercise testing",
        "cpet",
        "cpxt",
        "vo2max test",
        "metabolic cart test",
        "gas exchange test",
        "graded exercise test",
    ),
    "graded_exercise_test": (
        "graded exercise test",
        "gxt",
        "incremental exercise test",
        "incremental test",
        "ramp test",
        "step test",
        "maximal exercise test",
        "vo2max test",
    ),
    "ramp_test": (
        "ramp test",
        "ramp incremental test",
        "ramp protocol",
        "incremental test",
        "graded exercise test",
        "ftp ramp test",
        "vo2max ramp test",
    ),
    "lactate_test": (
        "lactate test",
        "blood lactate test",
        "lactate profile",
        "lactate curve",
        "incremental lactate test",
        "lactate threshold test",
        "step test",
    ),
    "critical_power_test": (
        "critical power test",
        "cp test",
        "critical power testing",
        "multiple time trial test",
        "three minute all out test",
        "3 minute all out test",
        "power duration test",
    ),
    "three_minute_all_out": (
        "three minute all out test",
        "3 minute all out test",
        "3mt",
        "3ao",
        "critical power test",
        "end test power",
        "ep",
    ),
    "wingate": (
        "wingate",
        "wingate test",
        "wingate anaerobic test",
        "want",
        "30 second wingate",
        "anaerobic power test",
        "peak power test",
    ),
    "sprint_test": (
        "sprint test",
        "maximal sprint test",
        "peak power test",
        "running sprint test",
        "cycling sprint test",
        "acceleration test",
    ),
    "one_rm_test": (
        "1rm test",
        "one repetition maximum test",
        "one rep max test",
        "maximal strength test",
        "maximum lift test",
        "direct 1rm",
    ),
    "countermovement_jump": (
        "countermovement jump",
        "counter movement jump",
        "cmj",
        "vertical jump",
        "jump test",
        "neuromuscular readiness",
        "jump height",
    ),
    "squat_jump": (
        "squat jump",
        "sj",
        "static jump",
        "concentric jump",
        "non countermovement jump",
    ),
    "drop_jump": (
        "drop jump",
        "depth jump",
        "dj",
        "reactive strength test",
        "reactive strength index",
        "rsi",
    ),
    "isometric_mid_thigh_pull": (
        "isometric mid thigh pull",
        "isometric mid-thigh pull",
        "imtp",
        "isometric strength test",
        "peak isometric force",
        "force time curve",
    ),
    "dynamometry": (
        "dynamometry",
        "dynamometer",
        "force measurement",
        "isokinetic dynamometry",
        "handgrip dynamometry",
        "strength testing",
    ),
    # -------------------------------------------------------------------------
    # BIOMECHANICS
    # -------------------------------------------------------------------------
    "biomechanics": (
        "biomechanics",
        "sport biomechanics",
        "sports biomechanics",
        "exercise biomechanics",
        "movement mechanics",
        "human movement mechanics",
        "kinematics",
        "kinetics",
    ),
    "kinematics": (
        "kinematics",
        "motion analysis",
        "movement analysis",
        "joint angles",
        "angular velocity",
        "linear velocity",
        "displacement",
        "movement pattern",
    ),
    "kinetics": (
        "kinetics",
        "force analysis",
        "joint moments",
        "joint torque",
        "ground reaction force",
        "mechanical power",
        "inverse dynamics",
    ),
    "ground_reaction_force": (
        "ground reaction force",
        "ground reaction forces",
        "grf",
        "vertical ground reaction force",
        "vgrf",
        "force plate",
        "force platform",
    ),
    "running_biomechanics": (
        "running biomechanics",
        "running mechanics",
        "running gait",
        "running form",
        "running kinematics",
        "running kinetics",
        "stride mechanics",
    ),
    "cycling_biomechanics": (
        "cycling biomechanics",
        "cycling mechanics",
        "pedaling mechanics",
        "pedalling mechanics",
        "pedal forces",
        "cycling kinematics",
        "bike fit",
    ),
    "stride_length": (
        "stride length",
        "step length",
        "running stride",
        "gait length",
        "distance per stride",
    ),
    "stride_frequency": (
        "stride frequency",
        "step frequency",
        "running cadence",
        "cadence",
        "step rate",
        "strides per minute",
    ),
    "ground_contact_time": (
        "ground contact time",
        "contact time",
        "stance time",
        "foot contact time",
        "gct",
    ),
    "vertical_oscillation": (
        "vertical oscillation",
        "vertical displacement",
        "vertical movement",
        "running bounce",
        "center of mass displacement",
        "centre of mass displacement",
    ),
    # -------------------------------------------------------------------------
    # INJURY, LOAD TOLERANCE, AND RETURN TO SPORT
    # -------------------------------------------------------------------------
    "injury_prevention": (
        "injury prevention",
        "injury risk reduction",
        "sports injury prevention",
        "prehabilitation",
        "prehab",
        "injury mitigation",
        "risk factor modification",
    ),
    "load_management": (
        "load management",
        "workload management",
        "training load management",
        "load monitoring",
        "fatigue management",
        "training dose management",
    ),
    "return_to_sport": (
        "return to sport",
        "return-to-sport",
        "rts",
        "return to play",
        "rtp",
        "return to performance",
        "sports rehabilitation",
    ),
    "tissue_capacity": (
        "tissue capacity",
        "load capacity",
        "load tolerance",
        "tissue tolerance",
        "physical capacity",
        "work capacity",
    ),
    # -------------------------------------------------------------------------
    # SPORT-SPECIFIC ENDURANCE TERMS
    # -------------------------------------------------------------------------
    "cycling": (
        "cycling",
        "cycle training",
        "bike training",
        "bicycle training",
        "road cycling",
        "track cycling",
        "mountain biking",
        "mtb",
        "indoor cycling",
        "ergometer cycling",
    ),
    "running": (
        "running",
        "run training",
        "distance running",
        "road running",
        "track running",
        "trail running",
        "cross country running",
        "treadmill running",
    ),
    "swimming": (
        "swimming",
        "swim training",
        "competitive swimming",
        "pool swimming",
        "open water swimming",
        "swim endurance",
    ),
    "rowing": (
        "rowing",
        "rowing training",
        "erg rowing",
        "rowing ergometer",
        "indoor rowing",
        "crew",
        "sculling",
    ),
    "triathlon": (
        "triathlon",
        "triathlon training",
        "multisport",
        "swim bike run",
        "ironman",
        "long course triathlon",
        "short course triathlon",
    ),
    "cross_country_skiing": (
        "cross country skiing",
        "cross-country skiing",
        "xc skiing",
        "nordic skiing",
        "ski endurance",
        "roller skiing",
    ),
    # -------------------------------------------------------------------------
    # COMMON ENDURANCE SESSION TYPES
    # -------------------------------------------------------------------------
    "long_run": (
        "long run",
        "long slow run",
        "long aerobic run",
        "endurance run",
        "easy long run",
        "weekly long run",
    ),
    "long_ride": (
        "long ride",
        "long aerobic ride",
        "endurance ride",
        "base ride",
        "easy long ride",
        "distance ride",
    ),
    "recovery_run": (
        "recovery run",
        "easy run",
        "regeneration run",
        "active recovery run",
        "shakeout run",
    ),
    "recovery_ride": (
        "recovery ride",
        "easy ride",
        "regeneration ride",
        "active recovery ride",
        "easy spin",
    ),
    "brick_training": (
        "brick training",
        "brick workout",
        "bike run",
        "bike-to-run",
        "transition training",
        "triathlon brick",
    ),
    "race_pace": (
        "race pace",
        "race intensity",
        "competition pace",
        "goal pace",
        "target pace",
        "event specific pace",
        "specific endurance",
    ),
    # -------------------------------------------------------------------------
    # ADAPTATION AND CELL SIGNALING
    # -------------------------------------------------------------------------
    "training_adaptation": (
        "training adaptation",
        "exercise adaptation",
        "physiological adaptation",
        "chronic adaptation",
        "training response",
        "exercise response",
        "adaptation to training",
    ),
    "ampk": (
        "ampk",
        "amp activated protein kinase",
        "amp-activated protein kinase",
        "energy sensing pathway",
        "endurance signaling",
        "endurance signalling",
    ),
    "mtor": (
        "mtor",
        "mammalian target of rapamycin",
        "mechanistic target of rapamycin",
        "mtorc1",
        "protein synthesis signaling",
        "protein synthesis signalling",
        "hypertrophy pathway",
    ),
    "pgc1alpha": (
        "pgc-1alpha",
        "pgc1alpha",
        "pgc1a",
        "pgc-1α",
        "peroxisome proliferator activated receptor gamma coactivator 1 alpha",
        "mitochondrial biogenesis",
        "endurance adaptation",
    ),
    "muscle_protein_synthesis": (
        "muscle protein synthesis",
        "mps",
        "myofibrillar protein synthesis",
        "protein synthesis",
        "muscle anabolism",
        "anabolic response",
    ),
    "satellite_cells": (
        "satellite cells",
        "muscle satellite cells",
        "muscle stem cells",
        "myonuclear addition",
        "myonuclei",
        "muscle regeneration",
    ),
    # -------------------------------------------------------------------------
    # HORMONAL AND AUTONOMIC RESPONSES
    # -------------------------------------------------------------------------
    "catecholamines": (
        "catecholamines",
        "adrenaline",
        "epinephrine",
        "noradrenaline",
        "norepinephrine",
        "sympathetic activation",
        "stress hormones",
    ),
    "cortisol": (
        "cortisol",
        "stress hormone",
        "glucocorticoid",
        "salivary cortisol",
        "serum cortisol",
        "catabolic hormone",
    ),
    "testosterone": (
        "testosterone",
        "serum testosterone",
        "free testosterone",
        "androgen",
        "anabolic hormone",
        "testosterone cortisol ratio",
    ),
    "autonomic_nervous_system": (
        "autonomic nervous system",
        "ans",
        "autonomic regulation",
        "sympathetic nervous system",
        "parasympathetic nervous system",
        "sympathovagal balance",
        "vagal activity",
    ),
    # -------------------------------------------------------------------------
    # BODY COMPOSITION
    # -------------------------------------------------------------------------
    "body_composition": (
        "body composition",
        "fat mass",
        "fat free mass",
        "lean body mass",
        "lean mass",
        "body fat percentage",
        "muscle mass",
    ),
    "lean_body_mass": (
        "lean body mass",
        "lbm",
        "lean mass",
        "fat free mass",
        "ffm",
        "muscle mass",
    ),
    "body_fat": (
        "body fat",
        "body fat percentage",
        "fat mass",
        "adiposity",
        "percent body fat",
        "adipose tissue",
    ),
    # -------------------------------------------------------------------------
    # STATISTICAL AND RESEARCH LANGUAGE
    # -------------------------------------------------------------------------
    "randomized_controlled_trial": (
        "randomized controlled trial",
        "randomised controlled trial",
        "rct",
        "controlled trial",
        "intervention study",
        "training intervention",
    ),
    "systematic_review": (
        "systematic review",
        "evidence synthesis",
        "research synthesis",
        "systematic literature review",
        "meta analysis",
        "meta-analysis",
    ),
    "meta_analysis": (
        "meta analysis",
        "meta-analysis",
        "pooled analysis",
        "quantitative synthesis",
        "effect size synthesis",
        "systematic review",
    ),
    "effect_size": (
        "effect size",
        "standardized mean difference",
        "standardised mean difference",
        "smd",
        "cohen's d",
        "hedges g",
        "magnitude of effect",
    ),
    "smallest_worthwhile_change": (
        "smallest worthwhile change",
        "swc",
        "smallest worthwhile difference",
        "smallest important difference",
        "minimal important difference",
        "mid",
    ),
    "minimal_detectable_change": (
        "minimal detectable change",
        "minimum detectable change",
        "mdc",
        "smallest detectable difference",
        "measurement error threshold",
    ),
    "reliability": (
        "reliability",
        "test retest reliability",
        "test-retest reliability",
        "repeatability",
        "reproducibility",
        "intraclass correlation coefficient",
        "icc",
        "coefficient of variation",
        "cv",
    ),
    "validity": (
        "validity",
        "criterion validity",
        "construct validity",
        "concurrent validity",
        "ecological validity",
        "measurement validity",
        "accuracy",
    ),
}


def get_domain_synonyms(term: str) -> tuple[str, ...]:
    """Retrieve synonym tuple for a given domain keyword."""
    key = term.lower().replace("-", "_").strip()
    return DOMAIN_SYNONYMS.get(key, ())


def expand_synonyms(terms: Sequence[str]) -> list[str]:
    """Expand recognized endurance domain terms with domain synonyms."""
    expanded: list[str] = list(terms)
    added: set[str] = {t.lower() for t in terms}

    for term in terms:
        synonyms = get_domain_synonyms(term)
        for syn in synonyms:
            if syn.lower() not in added:
                expanded.append(syn)
                added.add(syn.lower())

    return expanded
